name: Roof API Smoke Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install roof deps
        working-directory: roof
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint import
        working-directory: roof
        run: |
          python - <<'PY'
          import importlib
          ok=True
          for mod in ["app.util","app.segmentation"]:
              try:
                  importlib.import_module(mod)
                  print("imported",mod)
              except Exception as e:
                  ok=False
                  print("FAIL",mod,e)
          if not ok:
              raise SystemExit(1)
          PY

      - name: Check FastAPI routes
        working-directory: roof
        env:
          CI: true
        run: |
          python - <<'PY'
          from fastapi.testclient import TestClient
          from app.main import app
          client = TestClient(app)
          r = client.post('/segment')  # no file, should be 400/422/500
          assert r.status_code in (400,422,500)
          r2 = client.post('/segment_masks')
          assert r2.status_code in (400,422,500)
          print('routes OK')
          PY

